language: go
go:
  - 1.6.3
env:
  global:
    - TARGET_ARCH=amd64
    - CGO_ENABLED=1
  matrix:
    - TARGET_OS=linux
    - TARGET_OS=windows
addons:
  apt:
    packages:
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64-x86-64
before_deploy:
  - export GOARCH=$TARGET_ARCH GOOS=$TARGET_OS
deploy:
  provider: script
  script: $HOME/gopath/src/github.com/Lafeng/deblocus/static/deploy.sh
  on:
    branch: dev
